---
- hosts: dc

  tasks:
    - name: gather nxos interfaces facts
      nxos_facts:
        gather_subset: interfaces
        provider: "{{ nxosapi }}"
      register: gather_nxos_interfaces

    - set_fact: nxos_facts_interfaces={{ gather_nxos_interfaces.ansible_facts.ansible_net_interfaces }}
    
    - name: view output
      debug:
        msg: "{{ nxos_facts_interfaces }}"
   
    - name: save output results per device
      template:
        src: "./templates/port-dest-status-report.j2"
        dest: './reports/devices/{{inventory_hostname}}-nxos-interface-report.csv'
        owner: ansible
        group: ansible_users
        mode: 0777

    - name: create combinned report
      assemble:
        src: ./reports/devices
        dest: './reports/nxos-interface-report.csv'
        owner: ansible
        group: ansible_users
        mode: 0777