- hosts: enterprise

  tasks:

  - name: update the system
    yum:
      name: "*"
      state: latest
    register: linuxpatching


# Legacy Method - replaced by reboot module!
#  - name: restart system to finish applying patches.
#    shell: "sleep 5 && reboot"
#    async: 1
#    poll: 0
#    when: linuxpatching.changed
#
#  - name: wait for 10 seconds
#    pause:
#      seconds: 10
#    when: linuxpatching.changed
#
#  - name: wait for the system to reboot
#    wait_for_connection:
#      connect_timeout: 20
#      sleep: 5
#      delay: 5
#      timeout: 60
#    when: linuxpatching.changed

  - name: restart system to finish applying patches.
    reboot:
    when: linuxpatching.changed

  - name: validate system is up
    ping: